# Generated by Django 3.0.3 on 2020-02-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_doc',
        ),
    ]
