dist: bionic
language: python

python:
  - 3.8

env:
  - ESALE_SERVER_BACKEND: "127.0.0.1:8888"
    CLIENT_ID: "Jd5h7NrgqnckhvnhBp826VQdwtUFuHw7li89QZex"
    CLIENT_SECRET: "f7JjxGzEc45mBM6EpfmaxNQlYH4eMNOITcSjXyFG5EefcIHYcByMeSd77QUMNeoNwUy0wSnf3ucRbVAcahSINMZHWxlVV3kdW2d0gsmiPoQLszm4h5LnppsgqXyotQd"
    DJANGO_SUPERUSER_PASSWORD: admin
    DJANGO_SUPERUSER_USERNAME: admin
    DJANGO_SUPERUSER_EMAIL: admin@test.com

install:
  - pip install -r requirements.txt
  - python manage.py makemigrations auth_api
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createsuperuser --no-input
  - python manage.py runserver $ESALE_SERVER_BACKEND &
  - until curl -s $ESALE_SERVER_BACKEND; do sleep 5; done

script:
  - behave tests/features/token.feature
  - behave tests/features/ninja.feature

cache:
  - pip

