dist: bionic
language: python

python:
  - 3.7

node_js:
  - 10.15.2

node:
  - 13.5.0

addons:
  chrome: stable

sudo:
  true

env:
  - ESALE_SERVER_BACKEND: 127.0.0.1:8888
    CLIENT_ID: "QDnggmItR8jYiwrqSHzoeHbC0pM4dxUgBR44z4Bj"
    CLIENT_SECRET: "wuTb6ztWsxNAOVaizUxhTjqpR3ZXJYwoq5qhvm7LtWhhJP7iOilBFkpDdIrUA2TcQ40LkOod145OilEEp1tAaTP5i08b9yq3Yup9IfiV8Tp0sr5dJTnUppPPsgNiOUpv"
    DJANGO_SUPERUSER_USERNAME: admin
    DJANGO_SUPERUSER_PASSWORD: admin
    DJANGO_SUPERUSER_EMAIL: admin@test.com
    SELENIUM_HOST: 127.0.0.1

install:
  - cd backend/
  - sudo apt-get update -y
  - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  - source ~/.profile
  - source ~/.bashrc
  - nvm install v13.5.0
  - nvm use v13.5.0
  - pip install -r requirements.txt
  - yarn install-all
  - yarn selenium
  - python manage.py makemigrations accounts
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createsuperuser --no-input
  - python manage.py runserver $ESALE_SERVER_BACKEND &
  - until curl -s $ESALE_SERVER_BACKEND; do sleep 5; done

script:
  - nodejs -v
  - node -v
  - yarn acceptance-tests tests/acceptance/features/apiUsers/createUsers.feature


cache:
  - pip
  - yarn
