dist: bionic
language: python

python:
  - 3.7.5

env:
  - ESALE_SERVER_BACKEND: "127.0.0.1:8888"
    DJANGO_SUPERUSER_USERNAME: admin
    DJANGO_SUPERUSER_PASSWORD: admin
    DJANGO_SUPERUSER_EMAIL: admin@test.com

install:
  - cd backend/
  - pip install -r requirements.txt
  - python manage.py makemigrations accounts
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createsuperuser --no-input
  - python manage.py runserver $ESALE_SERVER_BACKEND &
  - until curl -s $ESALE_SERVER_BACKEND; do sleep 5; done

script:
  - pylint -j 3 accounts backend manage.py
  - python manage.py test accounts.tests

cache:
  - pip

