dist: bionic
language: python

python:
  - 3.8

env:
  - ESALE_SERVER_BACKEND="127.0.0.1:8888" CLIENT_ID="Jd5h7NrgqnckhvnhBp826VQdwtUFuHw7li89QZex" CLIENT_SECRET="f7JjxGzEc45mBM6EpkfmaxNQlYH4eMNOITcSjXyFG5EefcIHYcByMeSd77QUMNeoNwUy0wSnf3ucRbVAcahSINMZHWxlVV3kdW2d0gsmiPoQLszm4h5LnppsgqXyotQd"

install:
  - pip install -r requirements.txt
  - python manage.py makemigrations auth_api
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py createsuperuser --username admin --email admin@test.com
  - admin
  - python manage.py runserver 127.0.0.1:8888

cache:
  - pip
  - npm

