# Generated by Django 2.1.7 on 2019-02-25 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(default=0)),
                ('cart_qty', models.IntegerField(default=0)),
                ('cart_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('l_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 58, 35, 53783, tzinfo=utc), verbose_name='Registered Date')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('image', models.ImageField(default='default.jpg', upload_to='customer', verbose_name='Image(Customer)')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image', models.ImageField(default='default_item.jpeg', upload_to='item_images')),
                ('minimum_stock', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('location_in_store', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('disc_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disc_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_qty', models.IntegerField()),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque')], max_length=6)),
                ('purchase_datetime', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 58, 35, 53783, tzinfo=utc))),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cart')),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.CartItem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 58, 35, 53783, tzinfo=utc))),
                ('received', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque')], default='CASH', max_length=6)),
                ('type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SALE', 'SALE')], default='SALE', max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('timestamp', models.DateField(default=datetime.date(2019, 2, 25))),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('l_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 58, 35, 53783, tzinfo=utc), verbose_name='Registered Date')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('image', models.ImageField(default='default.jpg', upload_to='vendor', verbose_name='Image(Vendor)')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vendor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Transaction'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vendor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(default=0, null=True, to='dashboard.Item'),
        ),
    ]
