# Generated by Django 2.1.7 on 2019-06-06 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(default=0)),
                ('cart_qty', models.IntegerField(default=0)),
                ('cart_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 10, 29, 336058, tzinfo=utc), verbose_name='Registered Date')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('tot_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(default='default.jpg', upload_to='customer', verbose_name='Image(Customer)')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField(null=True)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_stock', models.IntegerField(blank=True, null=True)),
                ('location_in_store', models.TextField(blank=True, null=True)),
                ('buying_rate_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('selling_rate_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('item_image', models.ImageField(default='default_item.jpeg', upload_to='item_images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('disc_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disc_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 10, 29, 336058, tzinfo=utc))),
                ('received', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=6)),
                ('type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SALE', 'SALE'), ('PAYDUE', 'PAYDUE')], default='SALE', max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('timestamp', models.DateField(default=datetime.date(2019, 6, 6))),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=10)),
                ('month_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 10, 29, 336058, tzinfo=utc), verbose_name='Registered Date')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('tot_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(default='default.jpg', upload_to='vendor', verbose_name='Image(Vendor)')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vendor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(default=0, null=True, to='dashboard.Item'),
        ),
    ]
