# Generated by Django 2.1.7 on 2019-06-06 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 15, 30, 443702, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buying_rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 15, 30, 443702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 12, 15, 30, 443702, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
