# Generated by Django 2.1.7 on 2019-02-25 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatmonth',
            name='month_name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 17, 18, 45, 794643, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 17, 18, 45, 794643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 17, 18, 45, 794643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 17, 18, 45, 794643, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
