# Generated by Django 3.0.2 on 2020-01-31 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200131_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='returntransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 451639, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
