# Generated by Django 2.1.7 on 2019-05-10 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190510_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buying_rate_prev',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_rate_prev',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 11, 13, 26, 46310, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 11, 13, 26, 46310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 11, 13, 26, 46310, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
