# Generated by Django 2.1.7 on 2019-06-07 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190606_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 7, 55, 40, 853357, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 7, 55, 40, 853357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactionstat',
            name='timestamp',
            field=models.DateField(default=datetime.date(2019, 6, 7)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 7, 55, 40, 853357, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.IntegerField(null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
