# Generated by Django 2.1.7 on 2019-06-07 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190607_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 35, 44, 296212, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 35, 44, 296212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 35, 44, 296212, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.IntegerField(default=0, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
