# Generated by Django 2.1.7 on 2019-02-25 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190225_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 12, 42, 150423, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='f_name',
            field=models.CharField(default=None, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='l_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 12, 42, 150423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 12, 42, 150423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 12, 42, 150423, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='f_name',
            field=models.CharField(default=None, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='l_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
