# Generated by Django 2.1.7 on 2019-02-25 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190225_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 57, 8, 111046, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 57, 8, 111046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 57, 8, 111046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactionstat',
            name='timestamp',
            field=models.DateField(default=datetime.date(2019, 2, 26)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 57, 8, 111046, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
