# Generated by Django 2.1.7 on 2019-02-25 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190226_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_recvd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_payed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_recv_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_pay_due', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tot_items_sold', models.IntegerField(default=0)),
                ('tot_items_purchased', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 12, 58, 979491, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 12, 58, 979491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 12, 58, 979491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 12, 58, 979491, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
