# Generated by Django 2.1.7 on 2019-02-26 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190226_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 35, 44, 255525, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 35, 44, 255525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 35, 44, 255525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 35, 44, 255525, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
