# Generated by Django 2.1.7 on 2019-06-08 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190608_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 59, 24, 148775, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 59, 24, 148775, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='returnitems',
            name='item',
        ),
        migrations.AddField(
            model_name='returnitems',
            name='item',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 59, 24, 148775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 59, 24, 148775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 59, 24, 148775, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
