# Generated by Django 2.1.7 on 2019-06-10 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190610_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='return_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 8, 52, 47, 842398, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 8, 52, 47, 842398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 8, 52, 47, 842398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 8, 52, 47, 842398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 8, 52, 47, 842398, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
