# Generated by Django 2.1.7 on 2019-02-27 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190226_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 7, 34, 50, 453687, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 7, 34, 50, 453687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactionstat',
            name='timestamp',
            field=models.DateField(default=datetime.date(2019, 2, 27)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 7, 34, 50, 453687, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
