# Generated by Django 2.1.7 on 2019-06-10 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190610_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='return_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 19, 43, 19983, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 19, 43, 19983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 19, 43, 19983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 19, 43, 19983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 9, 19, 43, 19983, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
