# Generated by Django 2.1.7 on 2019-02-27 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190227_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 8, 2, 28, 890177, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 8, 2, 28, 890177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SALE', 'SALE'), ('PAYDUE', 'PAYDUE')], default='SALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 8, 2, 28, 890177, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
