# Generated by Django 2.1.7 on 2019-03-22 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190227_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 6, 25, 23, 851513, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 6, 25, 23, 851513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactionstat',
            name='timestamp',
            field=models.DateField(default=datetime.date(2019, 3, 22)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 6, 25, 23, 851513, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
