# Generated by Django 3.0.2 on 2020-01-31 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 10, 41, 17, 322613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 10, 41, 17, 322613, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
