# Generated by Django 3.0.2 on 2020-01-31 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200131_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 446536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 12, 39, 46, 446536, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
