# Generated by Django 2.1.7 on 2019-05-22 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190519_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 9, 42, 15, 769310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 9, 42, 15, 769310, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
