# Generated by Django 2.1.7 on 2019-03-22 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190226_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 6, 24, 39, 787836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 6, 24, 39, 787836, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
