# Generated by Django 2.1.7 on 2019-04-16 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190322_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 9, 5, 23, 980004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 9, 5, 23, 980004, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
